### PR TITLE
added the donation button!

### PR DESCRIPTION
**Pull request by yamilethmedina**
image

Wondering about the style of the button...I wanted to style it like the Get Involved button, but its class overrides all others and probably has an impact on the functionality of that donation plugin.

### CODE REVIEW

**Review by ErnieAtLYD — COMMENTED** [review]
I think this looks good but I don't know jade that well. @CristinaSolana?

**Comment by ErnieAtLYD** [comment]
Hey @yamilethmedina, the home page looks good. But I'm noticing if I go to the Get Started page the link doesn't work:

image

Any way we could move the "Donate to Code for Miami!" link right next to the "Code of Conduct" link in the footer?

**Comment by CristinaSolana** [comment]
@ernie Yeah, I plan on moving this off Jade so the barrier to entry is lower... I'm fine with the button where it is. We can always change next week. :)

**Comment by ernie** [comment]
@cristinasolana I think you meant @ernieatlyd. :)

**Comment by ErnieAtLYD** [comment]
@ernie Cool name, though. ;)

**Comment by ernie** [comment]
@ErnieAtLYD Likewise ;)

**Comment by yamilethmedina** [comment]
@ernieatlyd @cristinasolana I’m taking a look at it now. I think the JavaScript for the button needs to be on every single page, and that's why it doesn't work once you go to the Get Started page?

Jade isn’t that hard to learn tbh. The new version has a new name though, so since upgrading would take changing things around anyway, I guess there could be other options. Thanks!

Yamileth Medina

Web Developer: JavaScript, Ruby on Rails, HTML, CSS, PHP, and more!
https://www.github.com/yamilethmedina https://www.github.com/yamilethmedina
https://www.linkedin.com/in/yamilethmedina https://www.linkedin.com/in/yamilethmedina

**Pull request merged**
